{% set name = "tokenizers" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9525375582fd1912ac3caa2f727d36c86ff8c0c6de45ae1aaff90f87f33b907

build:
  number: 1
  skip: True  # [py<35 or win32 or (win64 and (rust_compiler == 'rust-gnu'))]
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib64/libgcc_s.so.1  # [linux]
    - $RPATH/ld64.so.1  # [s390x]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    # It's needed to find openssl
    - pkg-config
  host:
    - python
    - pip
    - setuptools-rust
    - setuptools
    - wheel
    - openssl {{ openssl }} # [linux]
  run:
    - python
    - openssl # [linux]

test:
  imports:
    - tokenizers
    - tokenizers.models
    - tokenizers.decoders
    - tokenizers.normalizers
    - tokenizers.pre_tokenizers
    - tokenizers.processors
    - tokenizers.trainers
    - tokenizers.implementations
    - tokenizers.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/tokenizers
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Fast State-of-the-Art Tokenizers optimized for Research and Production
  description: |
    Provides an implementation of today's most used tokenizers, with a focus on 
    performance and versatility.
  dev_url: https://github.com/huggingface/tokenizers
  doc_url: https://huggingface.co/docs/tokenizers/index

extra:
  recipe-maintainers:
    - anthchirp
    - hadim
    - ndmaxar
    - oblute
    - setu4993
